### PR TITLE
Change default identifiers dataset google drive id

### PR DESCRIPTION
**Pull request by irinakhismatullina**
Loaded new dataset (1 million identifiers, as before), changes:
1. Updated splits from the TokenParser.
2. Merged rows with equal splits.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@irinakhismatullina Did you use the freshly merged neural splitter?

**Comment by irinakhismatullina** [comment]
No, is it ready??? I didn't know that

**Comment by irinakhismatullina** [comment]
Did anybody check the quality? I would love to play with it, but after that I will probably have to restart all experiments from the zero point to get the best quality with the fresh data...

**Comment by vmarkovtsev** [comment]
The quality is the same as in the paper https://arxiv.org/abs/1805.11651

**Comment by vmarkovtsev** [comment]
Caution: it requires a GPU to work, otherwise you finish splitting one million by Christmas.

**Comment by irinakhismatullina** [comment]
I'm always using the cluster:) So, what's best to do: look at the new splitter right away, or first add everything I've done with the old one?

**Comment by vmarkovtsev** [comment]
Add the old stuff first, that's safer.

You can contact @glimow about using the model, that's him who worked on it.

**Comment by irinakhismatullina** [comment]
Then this PR can be merged.

**Pull request merged**
