### PR TITLE
Fix for CodeGenerator.gerenate() and FeatureExtractor._add_noops() if we remove labels with low support

### PR DESCRIPTION
**Pull request by zurk**
Depends on https://github.com/src-d/style-analyzer/pull/407

Both this methods relay that `y`-s in VirtualNode-s are the initial unfiltered targets. As soon as PR #407 make this filtering work we should fix these methods. 

Bug example for `FeatureExtractor._add_noops()`:
1. We filter `y` with value `⏎⏎⏎⏎⏎⏎⏎⏎⏎` and set it to `None`. `FeatureExtractor._add_noops()` see that `y=None` and adds NOOPs from both sides. 

Bug example for `CodeGenerator.gerenate()`:
2. We filter `y` with value `⏎⏎⏎␣⁻␣⁻␣⁻` and set `y=None`. Now we lose information about indentation change. Also `FeatureExtractor._add_noops()` inserts NOOPs between such VirtualNode and accumulated indentation. Both things confuse `CodeGenerator`.

So the main idea of PR is to add a new field to `VirtualNodes` called `y_original`. We set this field when any filtering is applied. 

PS: The fix is the ugliest one. And it is worth to include `y_original` to `VirtualNode.__init__()` feel free to ask me to do that if you have the same opinion.

### CODE REVIEW

**Comment by zurk** [comment]
My main worry about this PR is that Egor's evaluation report shows performance drop. I should check it with current mater to be 100% but if it is true, we should find a reason.

**Comment by zurk** [comment]
Just a note that as soon as we merge https://github.com/src-d/style-analyzer/pull/407 and not this PR a lot of stuff in the master is not going to work as expected

cc @vmarkovtsev @m09 

Feel free to ask me about any explanations you need.

**Comment by m09** [comment]
When we consider only a few lines of labeled nodes during `analyze` we do not remove `y` from all the other nodes. In the same vein here we should just add a test during the creation of `vnodes_y` that the class is in the supported labels and not touch their `y` attribute. This PR complicates an already unmaintainable part of the codebase so I don't feel comfortable with it.

**Comment by zurk** [comment]
ok, I'd like this way of solving the problem. Let me try.

**Comment by zurk** [comment]
I close this one and open new https://github.com/src-d/style-analyzer/pull/415 because it is completely different. Thanks, @m09 for a better solution!

**Pull request closed without merging**
