### PR TITLE
Remove redundant and bad bblfsh version

### PR DESCRIPTION
**Pull request by zurk**
I introduce this error yesterday :man_facepalming: 

@m09 please review it because Vadim has a coding day today.

### CODE REVIEW

**Comment by zurk** [comment]
I stopped Travis because there is nothing new to check.

**Comment by m09** [comment]
Reviewed and approved but I cannot merge, sorry.

**Comment by zurk** [comment]
Oh, only @vmarkovtsev authorized to merge now?

**Comment by m09** [comment]
yup

**Comment by vmarkovtsev** [comment]
I am happy this has not been merged because that's a hard constraint which is not listed in sourced-ml requirements. sourced-ml can work with an older client while the lookout core cannot.

**Comment by vmarkovtsev** [comment]
Oh wait now I see, it has been added at the top. Sorry.

**Pull request merged**
