### PR TITLE
Add the Rules class

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Merging this with failing 3.7 - @juanjux should release a new `bblfsh` version after https://github.com/bblfsh/client-python/pull/117 is merged tomorrow.

**Comment by juanjux** [comment]
@vadim, already tomorrow, merged.

**Comment by vmarkovtsev** [comment]
Cool! Tomorrow comes today

**Comment by vmarkovtsev** [comment]
@juanjux PyPi still shows the old version...

**Comment by juanjux** [comment]
@vmarkovtsev yep, no version bump in setup.py, no pypi version, I'll do a ninja commit.

**Comment by juanjux** [comment]
@vmarkovtsev [done](https://pypi.org/project/bblfsh/).

**Comment by vmarkovtsev** [comment]
All good

image

**Comment by vmarkovtsev** [comment]
@juanjux we need to run `setup.py --getdeps --log` to regenerate the protobuf python files. The current package contains the old ones and is equivalent to the previous version. How to check: `bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2.py` should contain `from bblfsh.github.com.gogo.protobuf.gogoproto import ...`.

**Comment by juanjux** [comment]
@vmarkovtsev done, try again with 2.11.1 and tell me if something else is missing (I checked that file after `--getdeps` and before bumping the version and it was as you posted).

**Comment by juanjux** [comment]
Looks like Python's 3.7 CI still fails :crying_cat_face:

**Comment by vmarkovtsev** [comment]
@juanjux Thanks, the new package version has the files updated and the build succeeded!

**Pull request merged**
