### PR TITLE
Add pysymspell submodule from #106 (1/6)

### PR DESCRIPTION
**Pull request by irinakhismatullina**
Signed-off-by: Irina Khismatullina <irenekhismatullina@gmail.com>

### CODE REVIEW

**Comment by m09** [comment]
By `x/5` I meant here for example `1/5`. :+1: otherwise!

**Comment by irinakhismatullina** [comment]
Travis is unhappy with pysymspell submodule code style:/

**Comment by vmarkovtsev** [comment]
What prevents us from requiring `git+https://github.com/ne3x7/pysymspell`? This is not an appropriate way to add the dependencies unless you have your custom patches which are not accepted mainstream, and even then you point to your repo in requirements and `setup.py`, e.g. https://mike.zwobble.org/2013/05/adding-git-or-hg-or-svn-dependencies-in-setup-py/

**Comment by irinakhismatullina** [comment]
I made changes to be able to save class instance inside asdf, and fixed code style. But afterwords I found the way to do it without editting, so now it is not required.

I will try adding this to requirements.txt, but I am not sure it will be able to setup.

**Comment by vmarkovtsev** [comment]
This is just a single file. Copy-paste it into your package and forget about it.

**Comment by m09** [comment]
well if there is no edit required it's probably better to have it in requirements no?

**Comment by vmarkovtsev** [comment]
@m09 There is no `setup.py` so it is useless to put it in the requirements.

**Comment by m09** [comment]
Indeed :/

**Comment by irinakhismatullina** [comment]
So can I do copy paste?

**Comment by zurk** [comment]
Guys, I really-really-really do not like the idea of copy-pasting.
So, I make a [fork](https://github.com/zurk/pysymspell), convert pysymspell into a package and [PR it back](https://github.com/ne3x7/pysymspell/pull/5). For now, we can work around it using `git+https://github.com/zurk/pysymspell` in requirements. I hope later my PR will be merged and we change it to `git+https://github.com/ne3x7/pysymspell`

**Comment by vmarkovtsev** [comment]
@zurk You should try coding Go to stop fearing copy-paste :trollface: I've got my antidote already.

Now seriously. Fork which is not going to be maintained (you won't - you are not the author) cannot be used. Once your PR is merged into the origin, we can leverage the package.

**Comment by zurk** [comment]
ok, it is fine.

**Pull request merged**
