### PR TITLE
Bump the package version

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
I am having troubles with passing the CI @zurk 
Travis networking works like a piece of sh*t today.

**Comment by zurk** [comment]
yeah, I see.

**Comment by vmarkovtsev** [comment]
`format.tests.test_expected_vnodes_number.ExpectedVnodesTest` seems to fail all the time on Py3.7

Even if I force the merge now, we will not be able to publish the package from the CI. Postponing to tomorrow.

**Comment by zurk** [comment]
I see that all tests are passed.

**Pull request merged**
