### PR TITLE
Add typos report

### PR DESCRIPTION
**Pull request by zurk**
Add 0.2.0 release report candidate

### CODE REVIEW

**Comment by zurk** [comment]
It is just an example of how the report will look like when we have a release.
Actually, we should add reports after the release is done to be 100% sure what we measure.

**Comment by vmarkovtsev** [comment]
The problem is that if the report breaks, we will have to delete the release and fix the report. So it is safer to report first and release second.

**Comment by zurk** [comment]
ok, fair enough. I am going to rerun it on current master.

**Comment by zurk** [comment]
The report was calculated by next command:
```bash
export NUM=20190411
docker rm -f bblfshd_style_analyzer_$NUM typos_report_gen_$NUM
docker run -d --rm --name bblfshd_style_analyzer_$NUM --privileged bblfsh/bblfshd:v2.12.0
docker exec bblfshd_style_analyzer_$NUM bblfshctl driver install --all
docker pull srcd/style-analyzer:github
docker run -it --link bblfshd_style_analyzer_$NUM -e LOOKOUT_BBLFSHD=ipv4://bblfshd_style_analyzer_$NUM:9432 --entrypoint bash -v /storage/konstantin/lookout-workdir/typos_reports_$NUM:/reports -v /backup:/backup --name typos_report_gen_$NUM -e BBLFSH srcd/style-analyzer:github
```
And inside the container:
```bash
apt update; apt install -y git make
export BRANCH=master
rm -rf style-analyzer/
git clone https://github.com/src-d/style-analyzer/
cd style-analyzer
git checkout $BRANCH
pip3 install -r requirements.txt
pip3 install modelforge==0.12.1
export TYPOS_REPORTS_DIR=/reports
export TYPOS_COMMITS_CACHE=/backup/repos_cache/
export JOBLIB_TEMP_FOLDER=/tmp

make typos-report
cd /reports/untagged/
tar -zcvf report.tar.gz commits_with_typo

```

**Pull request merged**
