### PR TITLE
Print rule hashes in the comments

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@warenlg This PR requires to regenerate the GitHub comment image; I will fix it using Gimp.

**Comment by warenlg** [comment]
why not generating it again ?

**Comment by vmarkovtsev** [comment]
05381b86 ␣ at column 6 should be removed.
f4b2f444 ␣ should be inserted at column 8.
3688cf1e ␣ should be inserted at column 13.

**Comment by zurk** [comment]
@vmarkovtsev Why do you decide to use hashes instead of Rule number for example? I find hashes not human-friendly.

**Comment by vmarkovtsev** [comment]
@zurk This is simple: rule indexes change from train to train, hashes do not.
Regarding friendliness, the whole Git is founded on hashes, and everybody loves them :)

**Pull request merged**
