### PR TITLE
Build visualizer in travis

### LINKED ISSUE #254: Build the visualizer in the CI
We need to `npm run build` our visualizer in Travis.

### PR DESCRIPTION
**Pull request by m09**
Fixes #254. Follow-up to #274 since travis didn't want to trigger a build for some reason.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@m09 Feel free to merge once you win the battle with Travis

**Comment by vmarkovtsev** [comment]
@m09 There was a syntax error in YAML (you cannot format lists this way) so Travis never started. Now is fine.

**Comment by vmarkovtsev** [comment]
@zurk Can you please fix flake8 errors in `server.py` since Hugo is on holidays. You should have enough permissions to push to his feature branch.

**Comment by zurk** [comment]
done

**Comment by m09** [comment]
Thanks for the fixes!

**Pull request merged**
