### PR TITLE
Turn on prune_attributes by default

### PR DESCRIPTION
**Pull request by zurk**

### CODE REVIEW

**Comment by zurk** [comment]
So, only +50-100% to test execution time. :) 
I expect the same performance drop on a Quality report and it can take more than 24h.

**Comment by vmarkovtsev** [comment]
@zurk @m09 We need to turn attributes pruning off individually in all the tests except one (to have it covered).

**Comment by zurk** [comment]
Yes, there is a more abstract issue for it: https://github.com/src-d/style-analyzer/issues/432

**Comment by m09** [comment]
Regarding specifically attributes pruning, see https://github.com/src-d/style-analyzer/pull/439#issue-237773135. I think we'll have to disable it everywhere for now.

**Pull request merged**
