### PR TITLE
Optimize style-analyzer tests 

### PR DESCRIPTION
**Pull request by zurk**
Test for noisy report mostly.

### CODE REVIEW

**Comment by zurk** [comment]
@vmarkovtsev do you want to merge style and test checks back? It also improves our Travis speed by 3-5 mins.

**Comment by zurk** [comment]
:muscle: 
image

**Comment by zurk** [comment]
It was accidentally closed.

**Comment by zurk** [comment]
Long tests check: https://travis-ci.org/zurk/style-analyzer/builds/503054071

**Comment by warenlg** [comment]
You could also decrease `n_iter` in the default test config to win even more time, no ?

**Comment by zurk** [comment]
Yes, it is true, but it is already 6. And actually we have 10 evaluations in random points, so setting less than 10 is the same.

**Comment by vmarkovtsev** [comment]
Which style and test checks? 🤔

**Comment by zurk** [comment]
We have two stages in Travis. The first one in style check (`flake8`) the second one is testing. One goes after another sequentially.  As soon as we have more slots in Travis we can do them in parallel as before to speed up Travis running time from ~19 mins to ~15 mins.

**Comment by vmarkovtsev** [comment]
Now I see what you mean, thanks. It saved much resources in the past, so I don't feel that we should revert this... It has an extra nice side effect that you have a fair chance to stop the Travis build before it occupies many slots.

**Comment by zurk** [comment]
Good point. :+1:

**Pull request merged**
