### PR TITLE
Add input file for quality report

### PR DESCRIPTION
**Pull request by zurk**
Closes: https://github.com/src-d/style-analyzer/issues/433#event-2065686017

Also you can run 
```bash 
cat data/quality_report_repos.csv | grep "url\|telescope" | \
    python3 -m lookout.style.format.benchmarks.top_repos_quality -o telescope_report -i -
```
to get report for telescope only.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@zurk Please do not do any refactoring until we discuss it tomorrow.

**Comment by zurk** [comment]
ok, I stop here for now.

**Comment by zurk** [comment]
Well, it is ready to be reviewed and merged if merging did not require a lot of additional work from your (@m09) or @EgorBu side. Because I assume that you are busy with big refactoring issues.

**Comment by zurk** [comment]
Rebased and ready for review.

**Comment by zurk** [comment]
Rebased one more time. Let's review and merge it?

**Pull request merged**
