### PR TITLE
Fix typos dataset generation error: case sensitivity

### PR DESCRIPTION
**Pull request by vmarkovtsev**
One month of running 4 machines, 12 cores each - for nothing :cry:

### CODE REVIEW

**Comment by zurk** [comment]
Test failed because of recent changes in modelforge: https://github.com/src-d/modelforge/commit/9e10ff214ad356d4073ebadd6374df961ee88975
because it expects to get each log entry at one line. I can fix it.

**Comment by zurk** [comment]
@vmarkovtsev https://github.com/src-d/style-analyzer/pull/766, but as I said in the PR description I do not like JSON formatting in case of logging.

**Comment by vmarkovtsev** [comment]
@irinakhismatullina PTAL https://travis-ci.com/src-d/style-analyzer/jobs/201648869#L4358

**Comment by irinakhismatullina** [comment]
numpy changed smth: https://github.com/automl/auto-sklearn/issues/667. Should I explicitly fix this argument everywhere, or to restrict the numpy version?

**Comment by vmarkovtsev** [comment]
As usual, fix it if easy, otherwise pin the version.

**Comment by vmarkovtsev** [comment]
@zurk The CI has finally passed.

**Pull request merged**
