### PR TITLE
Fix quality report generation

### PR DESCRIPTION
**Pull request by zurk**
On the trail of https://github.com/src-d/style-analyzer/pull/534

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@uzrk We need to check that our reports do work before launching them for the final time, can you please double-check.

**Comment by zurk** [comment]
@vmarkovtsev I glad to do that, but the only way to check it is to lunch it. It is what I am doing right now to clean up my bugs.

**Comment by zurk** [comment]
on https://github.com/storybooks/storybook and https://github.com/laravel/telescope 
it works well.

**Comment by zurk** [comment]
I am going to run it for the night to see if there anything else wrong.

**Comment by zurk** [comment]
@vmarkovtsev  I think it is worth to merge it now (after the second review) because this one contains a bunch of good fixes. If I found others I create a new PR.

**Comment by vmarkovtsev** [comment]
@zurk CI failed

**Comment by zurk** [comment]
Fixed. These tests are really annoying. Once it is better to rewrite it a little bit.

**Comment by zurk** [comment]
Finally 🎉

**Pull request merged**
