### PR TITLE
Remove logging args from args given to handlers

### PR DESCRIPTION
**Pull request by m09**

### CODE REVIEW

**Comment by m09** [comment]
ok. Then there must be some problem in setup.py because my version was not updated even though I ran `pip install .`

**Comment by m09** [comment]
they don't seem removed: https://github.com/src-d/lookout-sdk-ml/blob/master/lookout/__main__.py#L7

**Comment by vmarkovtsev** [comment]
I am talking about https://github.com/src-d/modelforge/blob/master/modelforge/slogging.py#L251

**Comment by vmarkovtsev** [comment]
@m09 I bet that Modelforge is not updated on your side because of the version conflict with sourced-ml. This is why we had to hack the CI, and also opened https://github.com/src-d/ml/issues/396

**Comment by m09** [comment]
yup ok, let's close then

**Pull request closed without merging**
