### PR TITLE
[WIP] Refactor typos corrector

### PR DESCRIPTION
**Pull request by irinakhismatullina**
- Change add_context_info function (supported outdated formats).
- Fix problems with _generate_tree in CandidatesGenerator (either some changes were made in modelforge since the code was written, or it was wrong from the beginning and was not tested then).
- Optimize `generate_candidates()` function in `CandidatesGenerator`.

**WIP**: small changes are added as the creation and saving/loading of TyposCorrector instances are tested after so many changes from several people and also changes in dependencies (modelforge and gensim and fastText and probably smth else).

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@irinakhismatullina This is growing too big, you need to split the PR into several parts once you are finished.

**Comment by irinakhismatullina** [comment]
I will, it wasn't meant to be so in the beginning

**Comment by vmarkovtsev** [comment]
Refactorings are like that ☣️

**Comment by irinakhismatullina** [comment]
Everything PRed in parts.

**Pull request closed without merging**
